version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      # saves the information for future use to this job and others that parse it.
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
    # this job reference the previous saved workspace, because it omits the run: echo command
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

# how the job should run
workflows:
  my_workflow:
    jobs:
    # for this job, it executes the job in save_hello_world first 
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output